version: "3.9"
services:
    qotoof:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: qotoofbe
        depends_on:
            - database
        ports:
            - 8000:8000
        # command: npx prisma db push
    database:
        image: mysql:latest
        container_name: dockersqlcompose
        hostname: localhost
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_TCP_PORT=4000
        ports:
            - 4000:4000
